version: "3"

services:
  synovia-db:
    image: postgres:alpine
    container_name: synovia-db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

volumes:
  pg_data:
