version: '3.7'

services:
  synovia-api:
    build: .
    container_name: synovia-api
    image: synovia-api
    restart: always
    depends_on:
      - synovia-db
    env_file:
      - .env
    environment:
      - DB_HOST=synovia-db
    volumes:
      - synovia-files:/usr/src/app/files
    networks:
      - default


  synovia-db:
    image: postgres:alpine
    container_name: synovia-db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    networks:
      - default

volumes:
    pg_data:
    synovia-files:

networks:
  default:
    external:
      name: homelab-network